<?php
// Allow requests from any origin
header("Access-Control-Allow-Origin: *");
header("Content-Type: text/plain; charset=utf-8");

// Check if question is provided
if (!isset($_REQUEST['question']) || empty(trim($_REQUEST['question']))) {
    http_response_code(400);
    die("Error: No question provided. Usage: ?question=Your+question+here");
}

// Sanitize input
$question = trim($_REQUEST['question']);

// Remote API endpoint and credentials
$remote_url = 'https://covalently-untasked-daphne.ngrok-free.dev/api/';
$user = 'jocarsa';
$password = 'jocarsa';
$model = 'phi3:latest'; // Changed to match working curl command

// Prepare request data
$data = [
    'user' => $user,
    'password' => $password,
    'question' => $question,
    'model' => $model,
];

// Send request to remote API
$options = [
    'http' => [
        'header'  => "Content-type: application/json\r\n",
        'method'  => 'POST',
        'content' => json_encode($data),
    ],
];
$context  = stream_context_create($options);
$result = file_get_contents($remote_url, false, $context);

if ($result === FALSE) {
    http_response_code(500);
    die("Error: Failed to connect to the remote API. Is it running?");
}

// Decode remote API's response
$response = json_decode($result, true);
if (json_last_error() !== JSON_ERROR_NONE) {
    http_response_code(500);
    die("Error: Invalid response from the remote API.");
}

// Extract and return the answer
if (isset($response['answer'])) { // Changed from 'response' to 'answer'
    echo $response['answer'];
} else {
    http_response_code(500);
    die("Error: No answer generated by the remote API. Raw response: " . $result);
}
?>
