<?php
// Allow requests from any origin (for curl/local testing)
header("Access-Control-Allow-Origin: *");
header("Content-Type: text/plain; charset=utf-8");

// Check if question is provided
if (!isset($_REQUEST['question']) || empty(trim($_REQUEST['question']))) {
    http_response_code(400);
    die("Error: No question provided. Usage: ?question=Your+question+here");
}

// Sanitize input
$question = trim($_REQUEST['question']);

// Ollama API endpoint (local)
$ollama_url = 'http://localhost:11434/api/generate';
$model = 'qwen3.5:4b';

// Prepare request data
$data = [
    'model' => $model,
    'prompt' => $question,
    'stream' => false, // Disable streaming for simplicity
];

// Send request to Ollama
$options = [
    'http' => [
        'header'  => "Content-type: application/json\r\n",
        'method'  => 'POST',
        'content' => json_encode($data),
    ],
];
$context  = stream_context_create($options);
$result = file_get_contents($ollama_url, false, $context);

if ($result === FALSE) {
    http_response_code(500);
    die("Error: Failed to connect to Ollama. Is it running?");
}

// Decode Ollama's response
$response = json_decode($result, true);
if (json_last_error() !== JSON_ERROR_NONE) {
    http_response_code(500);
    die("Error: Invalid response from Ollama.");
}

// Extract and return the answer
if (isset($response['response'])) {
    echo $response['response'];
} else {
    http_response_code(500);
    die("Error: No response generated by Ollama.");
}
?>
